# Generated by Django 5.0.7 on 2024-09-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=10000)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
