# Generated by Django 5.0.7 on 2024-08-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eight_One_Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=50)),
                ('lessone', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Eight_Two_Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=50)),
                ('lessone', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Nine_One_Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=50)),
                ('lessone', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Nine_Two_Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=50)),
                ('lessone', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Seven_One_Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=50)),
                ('lessone', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Seven_Two_Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=50)),
                ('lessone', models.CharField(max_length=40)),
            ],
        ),
    ]
