# Generated by Django 5.0.7 on 2025-06-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eight_one_absence',
            name='shamsi_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eight_two_absence',
            name='shamsi_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nine_one_absence',
            name='shamsi_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nine_two_absence',
            name='shamsi_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seven_one_absence',
            name='shamsi_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seven_two_absence',
            name='shamsi_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
