# Generated by Django 5.0.7 on 2025-06-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NineTwoBook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amadegi',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='arabic',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='computer',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='emla',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='english',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='farhang_honar',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='farsi',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fizik',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='kar_fan',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='maref',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='math',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='motaleat',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='negaresh',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quran',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shimi',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='varzesh',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='zist',
            name='score',
            field=models.CharField(max_length=10),
        ),
    ]
